{% set version = "0.14.1" %}

package:
  name: qtkeychain
  version: {{ version }}

source:
  url: https://github.com/frankosterfeld/qtkeychain/archive/{{ version }}.tar.gz
  sha256: afb2d120722141aca85f8144c4ef017bd74977ed45b80e5d9e9614015dadd60c

build:
  skip: true  # [win and vc<14]
  number: 0
  run_exports:
    - {{ pin_subpackage('qtkeychain', max_pin='x.x') }}

requirements:
  build:
    - pkg-config  # [unix]
    - cmake
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - qt-main
    - libsecret  # [linux]
    - zlib       # [linux]
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
    - qt-main
    - libsecret  # [linux]
    - zlib       # [linux]

test:
  commands:
    - test -f ${PREFIX}/lib/libqt5keychain${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_BIN%\\qt5keychain.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\qt5keychain.lib exit 1  # [win]

about:
  home: https://github.com/frankosterfeld/qtkeychain
  license: BSD-3-Clause
  license_file: COPYING
  summary: QtKeychain is a Qt API to store passwords and other secret data securely

extra:
  recipe-maintainers:
    - ceholden
    - gillins
