{% set version = "0.13.0" %}

package:
  name: qtkeychain
  version: {{ version }}

source:
  url: https://github.com/frankosterfeld/qtkeychain/archive/v{{ version }}.tar.gz
  sha256: 5c04ad1c2f1142197544ddbce249c73b45c724bd683e6dc89bdefbc8e6be36e7

build:
  skip: true  # [win and vc<14]
  number: 0
  run_exports:
    - {{ pin_subpackage('qtkeychain', max_pin='x.x') }}

requirements:
  build:
    - pkg-config  # [unix]
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - qt
  run:
    - qt

test:
  commands:
    - test -f ${PREFIX}/lib/libqt5keychain${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_BIN%\\qt5keychain.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\qt5keychain.lib exit 1  # [win]

about:
  home: https://github.com/frankosterfeld/qtkeychain
  license: BSD-3-Clause
  license_file: COPYING
  summary: QtKeychain is a Qt API to store passwords and other secret data securely

extra:
  recipe-maintainers:
    - ceholden
    - gillins
